language: php

php:
  - 5.4

before_script:
  - mv ../cakephp-codesniffer ../CakePHP && cd ../CakePHP
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit tests

notifications:
  email: false